# Docker Compose 定義ファイル (開発環境用)

version: '3.7'

services:
  # PostgreSQL データベースサーバ
  db:
    image: postgres
    restart: always
    networks:
      - appnet
    environment:
      POSTGRES_DB: im_pact
      POSTGRES_USER: im_pact
      POSTGRES_PASSWORD: arisu15
    ports:
      - 5432:5432
    volumes:
      - ./db_datas:/var/lib/postgresql/data

  # Adminer サーバ (PostgreSQL データベース管理用)
  adminer:
    build: ./.utils/adminer/
    depends_on:
      - db
    restart: always
    networks:
      - appnet
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 18080:8080

  # Redis データベースサーバ (キュー用)
  redis:
    container_name: redis
    image: redis:6.0-alpine
    command: redis-server --appendonly yes --requirepass arisu15
    restart: always
    networks:
      - appnet
    ports:
      - 6379:6379
    volumes:
      - './redis_datas:/data'

  # Bullboard サーバ (Redis データベース管理用)
  bullboard:
    image: deadly0/bull-board:1.0.0-alpha.7
    depends_on:
      - redis
    restart: always
    networks:
      - appnet
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: arisu15
      BULL_PREFIX: bull
    ports:
      - 18081:3000

networks:
  appnet:
